### ISSUE TITLE
Home page profile icons are super stretched [Minor]

### ISSUE THREAD

**Issue by sienasc** [info442-sp21/i-team#65]
**Describe the bug**
On the home page, the profile images are stretched and need to be resized.

**To Reproduce**
1. Go to 'https://covid19-immunization.web.app/about'
2. Scroll down to profile images

**Expected behavior**
For each image to be uniform

**Screenshots**
<img width="1602" alt="Screen Shot 2021-05-25 at 1 59 02 PM" src="https://user-images.githubusercontent.com/63016712/119567614-5e823100-bd61-11eb-9041-1a4808961dd8.png">

**Desktop (please complete the following information):**
 - OS: iOS 11.2.1
 - Browser: Safari
 - Version: Version 14.0.3 (16610.4.3.1.4)

**Comment by tichx** [comment]
@bphan23 just set all image to have a width of 100% will fix it.

img {
width: 100%
}

**Comment by bphan23** [comment]
Fixed stretched images in index.css

.circImg {
 width: 100%;
}

**Comment by juliashull** [comment]
https://github.com/info442-sp21/i-team/commit/adaee8f57c6a05bb5b1de887db3acb073a572183

**Comment by cherimarie** [comment]
BUG: ALL TEAM MEMBERS ARE VERY TALL 😆 

Just FYI, best practice for responsivity is for all images to have max-width set to 100%, preventing any overflow of their container. `img {max-width: 100%;}`
