### ISSUE TITLE
Visualizations Page. States [Minor]

### ISSUE THREAD

**Issue by sienasc** [info442-sp21/i-team#66]
**Describe the bug**
When you select a specific state (other than Washington), Washington should go back down to the other "W" states. Right now it stays at the top of the list.

**To Reproduce**
1. Go to  'https://covid19-immunization.web.app/about'
2. Click on 'Visualizations' tab
3. Click on state selector
4. Click any state other than Washington
5. 5. You'll notice that Washington stays at the top rather than joins its other "W" states

**Expected behavior**
I would expect that Washington would not stay at the top and instead be towards the bottom. This project doesn't seem to be focused just on Washington so it doesn't really make sense to leave it at the top.

**Screenshots**
<img width="555" alt="Screen Shot 2021-05-25 at 2 05 50 PM" src="https://user-images.githubusercontent.com/63016712/119568401-537bd080-bd62-11eb-88b7-7194fbafb3c6.png">

Desktop (please complete the following information):

OS: iOS 11.2.1
Browser: Safari
Version: Version 14.0.3 (16610.4.3.1.4)

**Comment by tichx** [comment]
This is by design. We want to set Washington state as default and appears always at the top.
