### ISSUE TITLE
Enhancement: Add descriptions/instructions under each table or chart on the visualization

### ISSUE THREAD

**Issue by drishtividyarthi** [info442-sp21/i-team#67]
It might be useful for you guys to include a description underneath each of the visualizations that explain to the user what the visualization is and how they can read it. For example for the table underneath the first visualization, you could add a couple sentences above it stating what selecting different dates does to the visualization so users can look at it and use the visualizations more effectively. 

I think this would be useful because the user would be able to understand more quickly what the visualizations are meant to do and how the user can use the visualizations to help them get the information they need to see more quickly. Without this description, I think the user would spend more time just playing around with it to see how the visualization changes before actually being able to get the information they need.

**Comment by juliashull** [comment]
This is a great suggestion and have decided to create descriptions for each visualization.

**Comment by tichx** [comment]
<img width="404" alt="WX20210530-172434@2x" src="https://user-images.githubusercontent.com/12144060/120125063-fb7f0880-c16b-11eb-8518-e61973032c10.png">

We've added the description for how to interact with the viz where it seems necessary in this commit be4e897
