### ISSUE TITLE
Submitting "Log my experience" feature request

### ISSUE THREAD

**Issue by ndemmel** [info442-sp21/i-team#68]
**Describe the feature request*
It would be nice to have a feature that confirms that the site has successfully saved the user's data after taking the vaccination survey. This could be a confirmation splash page, or anything else your team decides is appropriate. 

This feature would be useful to have to prevent users from uploading duplicate surveys in the event that they are unsure that their data went through the first time. This can also help prevent your data from becoming inaccurate. 

OS and browser: Windows 10 Firefox 88.0.1 (64-bit)

**Comment by juliashull** [comment]
As a team we decided that this enhancement was not necessary as after one completes the type form it tells them to redirect back to visualization page. Technically there is a confirmation page when you finish the type form.
