### ISSUE TITLE
Help users interact with the visualizations

### ISSUE THREAD

**Issue by atnguyenduy** [info442-sp21/i-team#69]
**Describe the bug**
There's no explanation on how users can interact with the visualizations and dataset. 

**To Reproduce**
1. Go to 'https://covid19-immunization.web.app/visualizations'
2. Scroll down to dataset
4. Add instructions

**Expected behavior**
A short 'about' or instruction on how to interact with dataset

**Screenshots**
![image](https://user-images.githubusercontent.com/41980535/119568776-b8cfc180-bd62-11eb-9a7b-a1e03500f534.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Lenovo Thinkpad laptop
 - Windows 10 Enterprise / Version 20H2 / OS build 19042.804
 - Browser: Edge
 - Version 90.0.818.56

**Comment by atnguyenduy** [comment]
Edit (accidentally put desktop information under Smartphone): 
**Desktop (please complete the following information):**
Device: Lenovo Thinkpad laptop
Windows 10 Enterprise / Version 20H2 / OS build 19042.804
Browser: Edge
Version 90.0.818.56

**Comment by tichx** [comment]
There is no expected interaction for the dataset. It is just a table that aims to provide information about vaccination progress. The only interaction happens at the top when users switch the state, the table will show corresponding information about that state. But I see it might be confusing why the table is here, therefore we will be adding a label/short description on top of the table to inform users that is a data table.

**Comment by tichx** [comment]
We fixed this issue 5ced24f4ddec0ca1881265d62caaf23b18c847c0 
<img width="1489" alt="WX20210527-200321@2x" src="https://user-images.githubusercontent.com/12144060/119923492-a1d9cc80-bf26-11eb-8afc-8fc7f37ef163.png">

**Comment by cherimarie** [comment]
I'd call this a feature request, as it would be an usability enhancement to the site.
