### ISSUE TITLE
New Feature Request: Ability to see more statistics on average daily vaccinations.

### ISSUE THREAD

**Issue by kristina-te** [info442-sp21/i-team#70]
Users can see average daily vaccinations over the span of x number of days and see trends with daily vaccinations as we monitor the development of COVID-19.  This could be helpful to understand the context of vaccinations happening at what rate and see how it might relate to the development of COVID-19.

**Comment by juliashull** [comment]
Although this is a great recommendation and would be a very helpful visualizations, as a team we have decided that we will not be making this enhancement. We will be spending our time enhancing the graphs and visuals that we currently have instead of creating new ones.

**Comment by tichx** [comment]
@kristina-te In our recent update d30ccdf, we actually added this feature! Now, you can view the daily vaccination average.
<img width="1665" alt="WX20210530-212249@2x" src="https://user-images.githubusercontent.com/12144060/120139476-64c34380-c18d-11eb-83d5-5403939f8438.png">
