### ISSUE TITLE
New Feature Request: Ability to change graph view for Common Reported Side Effects from COVID-19 Vaccines. 

### ISSUE THREAD

**Issue by kristina-te** [info442-sp21/i-team#71]
I think a bar graph option might be more helpful since the pie graph does not add up to 100%. Thus, it’s a little difficult to derive appropriate conclusions about side effects from this graph.

**Comment by tichx** [comment]
@kristina-te Good suggestion! We've updated the graph view to a bar chart instead in our latest commit ce09e39fb85f4712419a508cd224ebb857973973. 
**Desktop View**
<img width="861" alt="WX20210527-182106@2x" src="https://user-images.githubusercontent.com/12144060/119915960-751eb880-bf18-11eb-84b2-a9f8c4fdaa47.png">
**Mobile View**
<img width="375" alt="WX20210527-182124@2x" src="https://user-images.githubusercontent.com/12144060/119915982-7c45c680-bf18-11eb-8f9d-31a1e7614a4b.png">
