### ISSUE TITLE
Typeform Must select side effects

### ISSUE THREAD

**Issue by abq14** [info442-sp21/i-team#72]
**Describe the bug**
On the Typeform, I am required to select vaccine side effects. There's no option to select "No symptoms" or skip the question. 

**To Reproduce**
1. Go to 'Visualizations'
2. Click on 'Log My Experience'
3. Select any options, but make sure to answer Yes to "Have you been vaccinated"
4. Go to question 8: "Have you experienced any of the following side effects?This question is required. *"
5. Attempt to skip the question

**Expected behavior**
I can select an option of "No side effects" or skip the question

**Screenshots**
This is what shows up when I try to skip the question. 
![image](https://user-images.githubusercontent.com/30161847/119570101-845d0500-bd64-11eb-8b33-1c24e1f0dbaa.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version Version 90.0.4430.212

**Comment by tichx** [comment]
Thanks for the comment, will be adding a no side effect option

**Comment by tichx** [comment]
<img width="1173" alt="WX20210527-141025@2x" src="https://user-images.githubusercontent.com/12144060/119897495-55c26400-bef5-11eb-8bad-6744a70bc70f.png">
This is fixed now.
