### ISSUE TITLE
[Major] Pie Chart Visualization

### ISSUE THREAD

**Issue by jordanjones243** [info442-sp21/i-team#74]
**Describe the bug**
When looking at the Pie Chart visualizations, not every symptom fits within its chunk. For example, the swelling/redness in the arm statistic does not fit within its slice of the pie.

**To Reproduce**
1. Go to https://covid19-immunization.web.app/about
2. Click on Visualizations
3. Scroll down to the pie chart at the bottom
4. See that the swelling/redness text does not fit within the pie.

**Expected behavior**
The expected behavior is for every piece of text to fit within their respective pies, preferably centered within the pie.

**Screenshots**
<img width="317" alt="Screen Shot 2021-05-25 at 2 37 17 PM" src="https://user-images.githubusercontent.com/55807669/119571931-d43ccb80-bd66-11eb-8c9b-a9003153c456.png">

**Desktop (please complete the following information):**
Google Chrome Version 89.0.4389.128 (Official Build) (x86_64)

**Comment by tichx** [comment]
Will replace the pie chart with a bar chart to better display the data.

**Comment by tichx** [comment]
@jordanjones243 Hi Jordan thanks for your comment. We've fixed this issue with a different visualization view ( bar chart) in 
ce09e39fb85f4712419a508cd224ebb857973973

Please refer to Issue #71
