### ISSUE TITLE
No Validation On The Amount of Vaccinations

### ISSUE THREAD

**Issue by kmarshall98** [info442-sp21/i-team#75]
**Describe the bug**
When the user logs their experience they have a variety of questions to fill out, however a user is able to say they got the J&J vaccination twice and are not fully vaccinated. When the user selects J&J, the portal should automatically know that they could only get one and that also means they are fully vaccinated. 

**To Reproduce**
1. Go to the 'visualizations' page
2. Scroll to the bottom 
3. Click 'Log My Experience'
4. Select start and fill out the questions until you reach the question on "which vaccine have you gotten" - make sure you select that you've been vaccinated. 
5. Select J&J

**Expected behavior**
The portal should skip the question on whether you have been fully vaccinated and how many shots have you gotten.
<img width="714" alt="Screen Shot 2021-05-25 at 2 47 53 PM" src="https://user-images.githubusercontent.com/46639384/119572816-321de300-bd68-11eb-88a7-9b0f000874b1.png">
<img width="498" alt="Screen Shot 2021-05-25 at 2 48 16 PM" src="https://user-images.githubusercontent.com/46639384/119572848-3f3ad200-bd68-11eb-8d1b-1e8981dcc811.png">

**Desktop (please complete the following information):**
Safari on macOS BigSure version 11.2.3

**Comment by juliashull** [comment]
As a team, we believe that this is not a bug and is actually an enhancement. The Johnson and Johnson vaccine is an anomaly in that it only requires 1 shot. The question "are you fully vaccinated?" can be answered yes by all people who received the Johnson and Johnson vaccine recipients. If we removed the question we wouldn't be able to collect the data to the above question.
