### ISSUE TITLE
Mouse is vertical resize style when hovering over table [minor]

### ISSUE THREAD

**Issue by mariamatlick** [info442-sp21/i-team#77]
**Describe the bug**
When hovering over the table beneath the top graph under the "Visualizations" tab, the cursor switches from a pointer to the vertical resize cursor. This table allows you to click the different column headings to sort the results, but this is confusing when the mouse is the vertical resize because it indicates that you can make the table bigger/longer, not click on each heading. 

**To Reproduce**
1. Go to website
2. Click on Visualizations
3. Scroll down to the table/log underneath the top graph on this page
4. Hover mouse over the white header bar of the table
5. See error: mouse changes to vertical resize cursor, not a pointer to indicate you can click on the column headings
**Expected behavior**
When the mouse changed to vertical resize, I thought I could resize the table/make it bigger in some way, but that is an incorrect assumption! I now know that the mouse should change to indicate clicking on the table headers.

**Screenshots**
Unable to take a screenshot that includes my mouse! But, here is the table I am referring to
![image](https://user-images.githubusercontent.com/49167660/119573356-fa636b00-bd68-11eb-9efa-7b3d6a4908c3.png)

**Desktop (please complete the following information):**
Chrome Version: Version 90.0.4430.212 (Official Build) (64-bit)
Windows Version: 10.0.19041 Build 19041

**Comment by tichx** [comment]
This is fixed: we've changed the style of the cursor to default to prevent the assumption of resizing the column.
