### ISSUE TITLE
Enhancement: label the "log my experience" button

### ISSUE THREAD

**Issue by drishtividyarthi** [info442-sp21/i-team#78]
This button at the bottom of the page is a little unclear for the user as the user is not sure if their input will change the visualizations or what the app will do with their information. It would be beneficial to add one or two sentences underneath that button to explain what the purpose of this feature is to the user and why they should enter their experience. 
<img width="578" alt="Screen Shot 2021-05-25 at 2 53 14 PM" src="https://user-images.githubusercontent.com/55815122/119573344-f6374d80-bd68-11eb-8eee-a4aab7b28d9c.png">

Including an explanation of why you guys are asking people to share their experience will encourage people to share their experience and also give them a deeper insight into what you guys will be doing with the information and what the visualizations are showing.

**Comment by embascom** [comment]
Including Drishti's recommendation, I would potentially make this a sidebar that is constantly shown on the left or right side of the graphs so that at any point the user can upload their experience. This might encourage more users to upload their information.

**Comment by bphan23** [comment]
Added sentence telling users how their data is being used and how it affects the visualization.

https://github.com/info442-sp21/i-team/commit/e0cc0d6115def77daf56f8dfa76a364fa1915f09
