### ISSUE TITLE
Lack of feedback on graph when there is no data

### ISSUE THREAD

**Issue by brendantran** [info442-sp21/i-team#79]
**Describe the bug**
When looking at different COVID-19 Vaccines Others Are Getting, there isn't feedback for when there is no data present. 

**To Reproduce**
1. Go to the Visualizations tab
2. Select Native Americans and Alaska Natives
3. No graph appears or message stating that there isn't information.

**Expected behavior**
A message saying "There is no data available for this group"

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Chrome
 - Version 90.0.4430.93 (Official Build) (x86_64)

**Comment by tichx** [comment]
<img width="1427" alt="WX20210527-203305@2x" src="https://user-images.githubusercontent.com/12144060/119925742-dea7c280-bf2a-11eb-9f73-7b23b94d1d55.png">
We've fixed this issue in the recent commit 0f9c0d8b4f25a8a8b714590e71a11d2cccc773a5. We now put an empty state placeholder to indicate that there is no data for this group.
