### ISSUE TITLE
Check boxes in visualization table don't do anything [minor]

### ISSUE THREAD

**Issue by mariamatlick** [info442-sp21/i-team#80]
**Describe the bug**
In the table underneath the top graph on the "Visualizations" page, there are check boxes that allow you to select different rows in the table. It is unclear what selecting the rows does, because nothing happens. 

**To Reproduce**
1. Go to website
2. Click on Visualizations tab
3. Scroll down to the table underneath the top graph on the page
4. Select the checkboxes next to certain rows
5. See error: nothing changes and there is no indication of what this is supposed to do

**Expected behavior**
Maybe that selecting certain rows would change the graph to only use the data from the select rows. Instead, nothing changes or is explained what this is supposed to do

**Screenshots**
![image](https://user-images.githubusercontent.com/49167660/119573760-8ecdcd80-bd69-11eb-8906-c76989173707.png)

**Desktop (please complete the following information):**
Chrome Version: Version 90.0.4430.212 (Official Build) (64-bit)
Windows Version: 10.0.19041 Build 19041

**Comment by tichx** [comment]
won't fix: after digging into the underlying library for hours, I don't think we have the option to disable the checkbox. I did find a way to allow only one box to be checked rather than allowing users to check all the boxes. Our updated code will reflect that, but we won't able to totally diable the check boxes.

**Comment by tichx** [comment]
Fixed in be4e89736b77987e6eb80ca5eb651505d21fe583

**Comment by cherimarie** [comment]
@tichx if the library won't let you remove the checkboxes, you could just hide them with CSS.

**Comment by tichx** [comment]
> @tichx if the library won't let you remove the checkboxes, you could just hide them with CSS.

@cherimarie Yes, I've abandoned the library for rendering table. I've made a function myself that fixed this issue
